branch-defaults:
  default:
    environment: eb-project-env
    group_suffix: null
global:
  application_name: ebs-project-devops
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
