# Generated by Django 3.1 on 2024-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('listing_type', models.CharField(max_length=50)),
                ('area_in_sqft', models.DecimalField(decimal_places=2, max_digits=20)),
                ('no_of_rooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('property_type', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='property/')),
            ],
        ),
    ]
